[database]
host = "localhost"
port = "5432"
user = "user"
password = "password"
name = "database"

[memstore]
host = "localhost"
port = "6379"
password = "password"
database = 0

[limiter]
max = 10
expiration = 60